---
ID: "bd11bbab-4ff7-44d5-b021-02284ec93981"
Parent: "4e0c465d-4a11-49d6-b701-6b9b4adc3d5b"
Template: "5203732f-9512-4ade-8e02-0cb085c10454"
Path: /sitecore/content/Sample/Example/Settings/Site Grouping/Example/CORS/default
DB: master
BranchID: "f0e39dc1-6a4f-41ed-b0fe-b65bf09a1745"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171227T074543Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
