---
ID: "ea8582b1-eb01-4088-a3ed-d0bf2224c1f7"
Parent: "ab73e838-844d-4c2d-866e-a0ea8fbeb612"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/Sample/Example/Presentation/Rendering Variants/JSON Results/Default
DB: master
BranchID: "692e3473-3749-464c-845d-8d515419a63d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171227T074546Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
