---
ID: "28477869-9ce4-4668-8934-f0f971ffed97"
Parent: "62125064-a2a5-4fcc-8e40-b0456cf20a10"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Sample/Example/Example/gulp/tasks/watchJS
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/7CCA2FD4A9BC4263B0DE761006FB8D2F.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "d192849a-d2f2-4562-b96a-0d119664dfd6"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGd1bHBpZiBmcm9tICdndWxwLWlmJzsNCmltcG9ydCBlc2xpbnQgZnJvbSAnZ3VscC1lc2xpbnQnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCBmaWxlQWN0aW9uUmVzb2x2ZXIgZnJvbSAnLi4vdXRpbC9maWxlQWN0aW9uUmVzb2x2ZXInOw0KDQpndWxwLnRhc2soJ3dhdGNoLWpzJywgWydsb2dpbiddLCAoKSA9PiB7DQogICAgdmFyIGNvbmYgPSBjb25maWcuanM7DQogICAgcmV0dXJuIHdhdGNoKGNvbmYucGF0aCwgZnVuY3Rpb24oZmlsZSkgew0KICAgICAgICB2YXIgc3RyZWFtID0gZ3VscC5zcmMoZmlsZS5wYXRoKQ0KICAgICAgICAgICAgLnBpcGUoZXNsaW50KCkpDQogICAgICAgICAgICAucGlwZShlc2xpbnQuZm9ybWF0KCkpDQogICAgICAgICAgICAucGlwZShlc2xpbnQucmVzdWx0cyhyZXN1bHRzID0+IHsNCiAgICAgICAgICAgICAgICAvLyBDYWxsZWQgb25jZSBmb3IgYWxsIEVTTGludCByZXN1bHRzLg0KICAgICAgICAgICAgICAgIGlmIChyZXN1bHRzLmVycm9yQ291bnQgPT0gMCB8fCBjb25mLmVzTGludFVwbG9hZE9uRXJyb3IpIHsNCiAgICAgICAgICAgICAgICAgICAgZmlsZUFjdGlvblJlc29sdmVyKGZpbGUpOw0KICAgICAgICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKCdQbGVhc2UgZml4IGVycm9ycyBiZWZvcmUgdXBsb2FkaW5nIG9yIHNldCBlc0xpbnRVcGxvYWRPbkVycm9yOnRydWUnLnllbGxvdyk7DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgfSkpOw0KDQoNCiAgICAgICAgcmV0dXJuIHN0cmVhbTsNCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnanMtd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24oKSB7DQogICAgICAgIGdsb2JhbC5pc1dhdGNoaW5nID0gdHJ1ZTsNCiAgICAgICAgZ3VscC5ydW4oJ3dhdGNoLWpzJykNCiAgICB9KQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 1075
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T065213Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
