---
ID: "2055b923-620a-4acb-9a82-e7a85dbe49b3"
Parent: "62125064-a2a5-4fcc-8e40-b0456cf20a10"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Sample/Example/Example/gulp/tasks/watchHtml
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/C1DC78E7FA844E1B8166BA3323E3F018.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "18a8f795-370c-4e24-95fa-f62be78acc08"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCBmaWxlQWN0aW9uUmVzb2x2ZXIgZnJvbSAnLi4vdXRpbC9maWxlQWN0aW9uUmVzb2x2ZXInOw0KLy8NCg0KZ3VscC50YXNrKCd3YXRjaC1odG1sJywgWydsb2dpbiddLCAoKSA9PiB7DQogICAgdmFyIGNvbmYgPSBjb25maWcuaHRtbDsNCiAgICByZXR1cm4gd2F0Y2goY29uZi5wYXRoLCBmdW5jdGlvbihmaWxlKSB7DQogICAgICAgIGZpbGVBY3Rpb25SZXNvbHZlcihmaWxlKTsNCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnaHRtbC13YXRjaCcsIFsnbG9naW4nXSwNCiAgICBmdW5jdGlvbigpIHsNCiAgICAgICAgZ2xvYmFsLmlzV2F0Y2hpbmcgPSB0cnVlOw0KICAgICAgICBndWxwLnJ1bignd2F0Y2gtaHRtbCcpDQogICAgfSk=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 521
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T065211Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
