---
ID: "3d238766-208a-4ff5-bd08-7c6e6bc6f251"
Parent: "1c57288d-d6be-44f8-8cc3-071c8629fe6b"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/Sample/Example/Presentation/Layout Service/Default
DB: master
BranchID: "b002c2a2-6ded-4fcb-be63-dfc310d6bcf3"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171227T074547Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
